apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-build-and-push
spec:
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: https://github.com/EdisonSu768/tekton-golang-build-deploy
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: golang-build
      taskRef:
        name: golang-build
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source
      params:
        - name: package
          value: github.com/EdisonSu768/tekton-golang-build-deploy
    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - golang-build
      workspaces:
        - name: source
          workspace: source
      params:
        - name: image
          value: edisonsu768/golang-http-server
        - name: insecure_registry
          value: 127.0.0.1
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: golang-build-and-push-run
spec:
  pipelineRef:
    name: golang-build-and-push
  workspaces:
    - name: source
      persistentvolumeclaim:
        claimName: golang-source-pvc
