apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: golang-build-and-push
spec:
  workspaces:
    - name: sonar-settings
    - name: shared-workspace
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: https://github.com/EdisonSu768/tekton-golang-build-deploy
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: code-analysis
      taskRef:
       name: sonarqube-scanner
      runAfter:
        - git-clone
      workspaces:
       - name: source-dir
         workspace: shared-workspace
       - name: sonar-settings
         workspace: sonar-settings
      params:
       - name: SONAR_HOST_URL
         value: http://172.17.0.2:9000
       - name: SONAR_PROJECT_KEY
         value: com.github.edisonsu768.golang-http-server
    - name: golang-build
      taskRef:
        name: golang-build
      runAfter:
        - code-analysis
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: package
          value: github.com/EdisonSu768/tekton-golang-build-deploy
    - name: docker-build
      taskRef:
        name: docker-build
      runAfter:
        - golang-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: image
          value: edisonsu768/golang-http-server
        - name: insecure_registry
          value: 127.0.0.1
      script: |
        ls
        pwd
        sleep 3000
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: golang-build-and-push-run
spec:
  serviceAccountName: default
  pipelineRef:
    name: golang-build-and-push
  workspaces:
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: golang-source-pvc
    - name: sonar-settings
      emptyDir: {}
